services:
  scansnap:
    build:
      context: /home/ubuntu/plt/scansnap
    image: scansnap-linux:latest
    container_name: scansnap-linux
    restart: unless-stopped
    network_mode: host
    environment:
      SCAN_OUTPUT_DIR: /scans
      SCAN_LANGUAGE: deu+eng
      SCAN_RESOLUTION: "300"
      SCAN_MODE: Color
      SCAN_SOURCE: ADF Duplex
      SCAN_FORMAT: pdf
      TZ: Europe/Berlin
      SCANNER_NAME: ScanSnap iX500
      SCANNER_URL: http://10.112.10.11/eSCL
      SCANNER_PROTOCOL: escl
    volumes:
      - /home/ubuntu/plt/scans:/scans
